### ISSUE TITLE
which folder for -image_root ?

### ISSUE THREAD

**Issue by loveJasmine** [jiasenlu/HieCoAttenVQA#17]
should I set image_root  to the folder of unzipped train2014.zip?

**Comment by loveJasmine** [comment]
rzai@rzai00:~/prj/HieCoAttenVQA/prepro$ 
rzai@rzai00:~/prj/HieCoAttenVQA/prepro$ CUDA_VISIBLE_DEVICES=1 th prepro_img_vgg.lua -input_json ../data/vqa_data_prepro.json -image_root /media/rzai/ai_data/VQA-ALL/mscoco.org-visualqa.org/train2014 -cnn_proto ../image_model/VGG_ILSVRC_19_layers_deploy.prototxt -cnn_model ../image_model/VGG_ILSVRC_19_layers.caffemodel
{
  batch_size : 20
  gpuid : 6
  out_name_train : "../data/vqa_data_img_vgg_train.h5"
  out_name_test : "../data/vqa_data_img_vgg_test.h5"
  cnn_proto : "../image_model/VGG_ILSVRC_19_layers_deploy.prototxt"
  cnn_model : "../image_model/VGG_ILSVRC_19_layers.caffemodel"
  backend : "cudnn"
  image_root : "/media/rzai/ai_data/VQA-ALL/mscoco.org-visualqa.org/train2014"
  input_json : "../data/vqa_data_prepro.json"
}
Successfully loaded ../image_model/VGG_ILSVRC_19_layers.caffemodel
nn.Sequential {
  [input -> output]
}
/home/rzai/torch/install/bin/luajit: /home/rzai/torch/install/share/lua/5.1/nn/Sequential.lua:29: index out of range
stack traceback:
	[C]: in function 'error'
	/home/rzai/torch/install/share/lua/5.1/nn/Sequential.lua:29: in function 'remove'
	prepro_img_vgg.lua:41: in main chunk
	[C]: in function 'dofile'
	...rzai/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670
rzai@rzai00:~/prj/HieCoAttenVQA/prepro$

**Comment by loveJasmine** [comment]
I figured it out!

**Comment by the-purple-demon** [comment]
plz tell which folder should be used for -image_root ?
