### ISSUE TITLE
The input of VGG19

### ISSUE THREAD

**Issue by WERush** [jiasenlu/HieCoAttenVQA#2]
Hi,
I am confused about the image size of the VGG19, in https://github.com/jiasenlu/HieCoAttenVQA/blob/master/prepro/prepro_img_vgg.lua#L107, i find the size of input of VGG19 is 3x448x448, but the VGG19.prototxt shows the model needs a image size --  3x224x224,  maybe I lost some information, hope you can help me.

**Comment by jiasenlu** [comment]
Hi, we enlarge the image to get larger feature map of conv5. (14 by 14 instead of 7 by 7.) If you follow the code, I think it should be fine. (just remove the fully connected layer of VGG). 

What error do you get?

**Comment by WERush** [comment]
So i need to modify the VGG19.prototxt to meet the needs of larger features, specifically, i need to change the input_shape{batch,3,224,224} to {batch,3,448,448}, isn't it?

**Comment by jiasenlu** [comment]
I think if you just follow the prepro code, everything will be fine. https://github.com/jiasenlu/HieCoAttenVQA/tree/master/prepro

**Comment by WERush** [comment]
I think i have a misunderstanding of the input of VGG19, and now i have got what i am wrong with. Thanks
