### ISSUE TITLE
Assertion `t >= 0 && t < n_classes failed

### ISSUE THREAD

**Issue by panfengli** [jiasenlu/HieCoAttenVQA#28]
I followed the tutorial, until `th train.lua`, I met a error as:

`libraries/torch/extra/cunn/lib/THCUNN/ClassNLLCriterion.cu:52: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [2,0,0] Assertion `t >= 0 && t < n_classes` failed.`

Wish for your help.

**Comment by panfengli** [comment]
I find the problem. The author originally use `-1` as the label for the error answer (`prepro_vqa.py`). But recently, the `ClassNLLCriterion.cu` has changed, as it added in a assertion as `t >= 0 && t < n_classes`.

**Comment by mrfarazi** [comment]
How did you fix the error? I am having the same problem.

**Comment by panfengli** [comment]
Since when I changed the label for `error` as `0`, the error still existed. So I finally set the `--num_ans` in `prepro_vqa.py` as `999` and make a little change as:

```
# get top answers
top_ans = get_top_answers(imgs_train, params)
atoi = {w:i+1 for i,w in enumerate(top_ans)}
atoi['error label'] = 1000 # ClassNLLCriterion.cu: Assertion `t >= 0 && t < n_classes`
itoa = {i+1:w for i,w in enumerate(top_ans)}
itoa[1000] = 'error label' # ClassNLLCriterion.cu: Assertion `t >= 0 && t < n_classes`
```

```
def encode_answer(imgs, atoi):
    N = len(imgs)
    ans_arrays = np.zeros(N, dtype='uint32')

    for i, img in enumerate(imgs):
        #ans_arrays[i] = atoi.get(img['ans'], -1) # -1 means wrong answer.
        ans_arrays[i] = atoi.get(img['ans'], 1000) # 1000 means wrong answer.

    return ans_arrays
```

**Comment by mrfarazi** [comment]
Thanks for your solution. Its working now. Cheers!

**Comment by Lionelding** [comment]
check the if your number of output classes is right
