### ISSUE TITLE
The accuracy is weird

### ISSUE THREAD

**Issue by JamesChuanggg** [jiasenlu/HieCoAttenVQA#3]
Hi all, I run this code with alternating attention and VGG feature and the output accuracy is weird.
Here is what it looks like
![](http://i.imgur.com/ZgOUlfu.jpg)
It supposed to be 60.5 according to the paper.
Btw in step of downloading image model, I didn't see ```image_model``` folder.

**Comment by rohit789123** [comment]
There is no image_model folder

Thanks

**Comment by JamesChuanggg** [comment]
Thanks for the reply. Btw is there codes for **attention visualization**?
Since readme mentioned it but I couldn't find the code for it.

**Comment by idansc** [comment]
Are we waiting for image_model folder or i'm missing something?

**Comment by idansc** [comment]
It seems like there is a bug in the model, since it almost always produce "yes" as the answer. Not sure what the bug is yet.
