### ISSUE TITLE
image_model folder

### ISSUE THREAD

**Issue by JamesChuanggg** [jiasenlu/HieCoAttenVQA#5]
Hi, 
When will you release codes in ```image_model``` folder since we need it to extract both vgg and residual feature.
I keep waiting for it since the previous issue.
For example, in ```prepro_img_residule.lua```, we miss ```transforms.lua``` in  ```image_model``` folder.
```lua
local t = require 'image_model.transforms'
```
Hope it will come out soon.

**Comment by jiasenlu** [comment]
Hi 

you can download the image_model.transforms from 

https://github.com/facebook/fb.resnet.torch/blob/master/datasets/transforms.lua

The image_model folder only contain the download script. I'll update them now. 

Thanks

Jiasen
