### ISSUE TITLE
Preprocessing images with ResNet

### ISSUE THREAD

**Issue by ilija139** [jiasenlu/HieCoAttenVQA#6]
$ Torch: not enough memory: you tried to allocate 123GB.
Happens here `prepro_img_residule.lua:98: in main chunk`, i.e.

```local feat_train=torch.FloatTensor(sz, 14, 14, 2048) --ndims)```

Do you really have 123GB+ RAM? 😃 

Anyway, why 14x14x2048? Shouldn't be 7x7x2048?

**Comment by ilija139** [comment]
Oh, is it because you scale the images to 448 instead 224?

**Comment by jiasenlu** [comment]
Actually, yes, and that's why I only trained the model once. ;)

I'm training the version 2 code now, which include CNN part. In that case you don't need that much RAM

**Comment by dhivyaprp** [comment]
Can we get a link to version 2 code. I don't have 128 GB RAM. I am getting a memory error when i try to extract feature for whole MSCOCO dataset
